### ISSUE TITLE
Type mismatch in v-model

### ISSUE THREAD

**Issue by dovca** [cogor/vue-formulate-datepicker#26]
The datepicker only seems to work with the `v-model` directive. Explicit `:value` and `@input` bindings fail to function properly. This is a problem, because the input data to the datepicker must be a `Date` instance and the output data is a string in a `YYYY-MM-dd` format. This just feels wrong and causes problems when using TypeScript.

Current workaround is to provide some kind of a proxy to `v-model` that parses the datestring to a proper `Date` instance.

In the following sandbox you can see that even though I'm explicitly setting `this.date` to a `Date` instance, it immediately changes to a string. https://codesandbox.io/s/delicate-cache-lezm1?file=/src/App.vue

**Comment by cogor** [comment]
@dovca Can you fix sandbox?

**Comment by dovca** [comment]
Oops, my bad, should be fine now

**Comment by cogor** [comment]
@dovca `:value` and `@input` binding fixed in v0.1.17
vue-formulate date validator working only with date in format YYYY-MM-dd, right now I don't know how fix it.
Sorry for the long wait 😔
