### ISSUE TITLE
Set date on input when editing

### ISSUE THREAD

**Issue by britisharmy** [cogor/vue-formulate-datepicker#8]
I have this code i am using to show date

```
 <FormulateInput
          language="en"
          name="checkin"
		  input-class="form-control"
          type="datepicker"
          v-model="checkin">
        </FormulateInput>
```

If my v-model checkin contains a date i set on previous page, how can i restore the value and show it on the date picker and input field?

**Comment by cogor** [comment]
@britisharmy  Thanks for you report, fixed in version 0.1.14
